
export { AlumnoModel } from './Alumno.js'
export { CentroEducativoModel as CentroModel } from './CentroEducativo.js'
export { ContenidoPracticoModel as CPModel } from './ContenidoPractico.js'
export { ContenidoTeoricoModel as CTModel } from './ContenidoTeorico.js'
export { EvaluativoModel } from './Evaluativo.js'
export { FichaParticularModel as FParticularModel } from './FichaParticular.js'
export { FichaProfesionalModel as FProfesionalModel } from './FichaProfesional.js'
export { LeccionModel } from './Leccion.js'
export { ProgresoAlumnoModel as PAlumnoModel} from './ProgresoAlumno.js'
export { ProgresoEvaluacionModel as PEvaluacionModel} from './ProgresoEvaluacion.js'
export { ProgresoLeccionModel as PLeccionModel} from './ProgresoLeccion.js'
export { ProgresoSeccionModel as PSeccionModel} from './ProgresoSeccion.js'
export { RoleModel } from './Role.js'
export { SeccionModel } from './Seccion.js'
export { UsuarioModel } from './Usuario.js'
